[package]
name = "ray-tracer-challenge"
version = "0.1.0"
authors = ["Przemyslaw Kaminski <przemyslaw.m.kaminski@gmail.com>"]
edition = "2021"

[lib]
name = "raytracer"
crate-type = ["rlib"]

[dependencies]
bincode = "2.0.0-rc.3"
clap = { version = "4.3.11", features = ["derive"] }
image = "0.24.6"
indicatif = { version = "0.17.3", features = ["rayon"] }
rayon = "1.7.0"
yaml-rust = "0.4.5"

[dev-dependencies]
rstest = "0.17.0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
